config/routes.rb
Rails.application.routes.draw do

  root 'properties#index'

  resources :properties, shallow: true do
    resources :photos do
      get :download, on: :collection
    end
  end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :property
  attachment :file, type: :image

  def self.watermark_image_path
    "#{Rails.root}/app/assets/images/watermark/logo.png"
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :photos, dependent: :destroy
  accepts_attachments_for :photos, append: true

  validates :title, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:edit, :update, :destroy]

  def index
    @photos = current_property.photos
  end

  def edit; end

  def update
    if @photo.update(photo_params)
      redirect_to @photo
    else
      render :edit
    end
  end

  def destroy
    if @photo.destroy
      redirect_to @photo.property, notice: 'Success!'
    end
  end

  def download
    photos = current_property.photos
    archive = ArchivePhotosService.new(photos).call

    response.headers['Content-Length'] = archive.size.to_s
    send_file archive, { type: 'application/zip', disposition: 'attachment', filename: 'Photos.zip' }

    archive.close
  end

  private

    def photo_params
      params.require(:photo).permit(:file, :caption)
    end

    def set_photo
      @photo = Photo.find(params[:id])
    end

    def current_property
      @property ||= Property.find(params[:property_id])
    end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  def index
    @properties = Property.all
  end

  def edit; end
  def show; end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)

    if @property.save
      redirect_to @property, notice: 'Property was successfully created.'
    else
      :new
    end
  end

  def update
    if @property.update(property_params)
      redirect_to @property, notice: 'Property was successfully updated.'
    else
      render :show
    end
  end

  private

    def property_params
      params.require(:property).permit(:title, :description, photos_files: [])
    end

    def set_property
      @property ||= Property.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uplowd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for [@property, @photo] do |f| %>
  <%= f.attachment_field :file, direct: true, presigned: true, multiple: true %>
  <%= f.submit %>
<% end %>

app/views/photos/edit.html.erb
<h1>EDIT</h1>

<%= render 'form' %>

app/views/photos/index.html.erb
<ul class="nav nav-pills" style="margin: 15px 0;">
  <li>
    <%= link_to 'New Photo', new_property_photo_path(current_property) %>
  </li>
</ul>

<div class="row">
  <% @photos.each do |photo| %>
    <div class="col-sm-3">
      <div class="photo">
        <%= image_tag attachment_url(photo, :file, :fill, 300, 300, format: 'jpg'), class: 'img-responsive img-rounded' %>
      </div>

      <div class="btn-group btn-group-sm" style="margin-top: 20px;">
        <%= link_to 'Details', photo, class: 'btn btn-default' %>
        <%= link_to 'Delete', photo, method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<h1>NEW</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<h1>SHOW</h1>

<%= image_tag attachment_url(@photo, :file, :fill, 300, 300, format: 'jpg') %>
<%= image_tag attachment_url(@photo, :file, :fill, 150, 150, format: 'jpg') %>
<%= image_tag attachment_url(@photo, :file, :fill, 75, 75, format: 'jpg') %>
<p><%= @photo.caption %></p>

<%= link_to 'All Photos', photos_path %>
<%= link_to 'Edit Photo', edit_photo_path(@photo) %>

app/views/properties/_form.html.erb
<%= simple_form_for @property do |f| %>
  <%= f.error_notification %>

  <fieldset>
    <legend>Details</legend>

    <%= f.input :title %>
    <%= f.input :description %>
  </fieldset>

  <%= f.button :submit %>
<% end %>

<%= render 'photos' %>
<%= render 'components/upload_photos_dialog' %>

app/views/properties/_photos.html.erb
<fieldset style="margin-top: 40px;">
  <legend>Photos</legend>

  <ul class="nav nav-pills" style="margin-bottom: 20px;">
    <li>
      <%= link_to 'Upload', '#', class: 'js-btn-upload-photos-dialog' %>
    </li>
    <li>
      <%= link_to 'Download', download_property_photos_path(@property) %>
    </li>
  </ul>

  <% @property.photos.each do |photo| %>
    <div class="col-sm-2">
      <div class="photo" style="margin-bottom: 10px;">
        <%= image_tag attachment_url(photo, :file, :watermark, 200, 200, format: 'jpg'), class: 'img-responsive img-rounded' %>
      </div>

      <div class="text-center">
        <%= link_to 'Delete', photo, method: :delete, class: 'btn btn-xs btn-default', data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</fieldset>

app/views/properties/index.html.erb
<div class="page-header">
  <h2><%= Property.all.count %> Properties</h2>
</div>

<ul class="nav nav-pills" style="margin: 15px 0;">
  <li>
    <%= link_to 'New Property', new_property_path %>
  </li>
</ul>

<div class="row">
  <% @properties.each do |property| %>
    <div class="col-sm-3">
      <div class="photo">
        <%= link_to property do %>
          <% if property.photos.exists? %>
            <%= image_tag attachment_url(property.photos.first, :file, :fill, 300, 300, format: 'jpg'), class: 'img-responsive img-rounded' %>
          <% else %>
            <%= image_tag 'default.jpg', class: 'img-responsive img-rounded' %>
          <% end %>
        <% end %>
      </div>

      <h4><%= property.title %></h4>
      <p><%= property.description %></p>
    </div>
  <% end %>
</div>

app/views/properties/new.html.erb
<div class="page-header">
  <h2>New Property</h2>
</div>

<ul class="nav nav-pills" style="margin: 15px 0;">
  <li>
    <%= link_to 'Back to Properties', properties_path %>
  </li>
</ul>

<%= render 'form' %>

app/views/properties/show.html.erb
<div class="page-header">
  <h2><%= @property.title.titleize %></h2>
</div>

<ul class="nav nav-pills" style="margin: 15px 0;">
  <li>
    <%= link_to 'Back to Properties', properties_path %>
  </li>
  <li>
    <%= link_to 'Download Photos', download_property_photos_path(@property) %>
  </li>
</ul>

<%= render 'form' %>